# Version of the Docker Compose syntax
version: "3.9"

# This is just the service that is going to run our Dockerfile
services:
  app:
    # This will build the Dockerfile into the current directory
    build:
      context: .
      # This will add our requirements.dev.txt file to allow the dependencies of development
      args:
        DEV: "True"
    # This maps port 8000 on our local machine to 8000 on our Docker container
    ports:
      - "8000:8000"
    # Map directories from our system to our Docker container
    volumes:
      - ./app:/app
    # This will help to run the server
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
