#configurations for github actions

# dash lines represents that it is a yaml file.
---
# this name is going to appear in github actions
name: checks

#trigger on push
on: [push]

#create a job where I'll give the name of job and where it will be running on. run-on is an operating system where we'll be running our job on over github. 
#steps - different things that will be running for the job.
#name of the step and then logging credentials for docker and then checkout, tests and lint as well to run.
jobs: 
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"